version: '3.1'

services:
  php:
    build:
      context: "./docker/php"
    volumes:
      # Place mysql dump in mysql folder for automatic import
      - "./mysql:/docker-entrypoint-initdb.d"
    restart: always
    volumes:
      - "./:/var/www/html"
    ports:
      - "8000:80"
